services:
  minio-dev:
    container_name: files-minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-storage-dev:/data
    environment:
      MINIO_ROOT_USER: dominium
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data

  postgres-files-dev:
    container_name: postgres-files
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: files
      PGDATA: /data/postgres
    volumes:
      - postgres-files-volume-dev:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  minio-storage-dev: {}
  postgres-files-volume-dev: