services:
  minio-files:
    container_name: files-minio
    image: minio/minio
    ports:
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: dominium
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data
    networks:
      - general

  postgres-files:
    container_name: postgres-files
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: files
      PGDATA: /data/postgres
    volumes:
      - postgres-files-volume:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - general
    restart: unless-stopped

  xml-validator:
    image: backend:latest
    container_name: xml-validator
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8088:8088"
    networks:
      - general
    depends_on:
      - postgres-files
      - minio-files

volumes:
  minio_storage: {}
  postgres-files-volume:

networks:
  general:
    driver: bridge