server:
  port: 8088
spring:
  application:
    name: xml-validator
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/files
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
      show-sql: true
minio:
  endpoint: "http://localhost:9000"
  user: "dominium"
  password: "Strong#Pass#2022"
  bucket: "xsd-files"